import type {
  Member, Provider, Claim, DashboardMetrics, SavingsDataPoint,
  USSDStats, DemoScenario, TrustBadge,
} from '@/types';

// ─── Members ──────────────────────────────────────────────────────────────────

export const MEMBERS: Member[] = [
  {
    id: 'mem-001',
    memberNumber: 'CIM-0291847',
    name: 'Tendai Moyo',
    plan: 'GOLD',
    city: 'Bulawayo',
    annualBenefit: 2500,
    benefitUsed: 652.50,
    conditions: [],
    phone: '+263 77 291 8470',
    email: 'tendai.moyo@email.co.zw',
    dateOfBirth: '1985-03-14',
  },
  {
    id: 'mem-002',
    memberNumber: 'CIM-0441209',
    name: 'Joseph Chikwanda',
    plan: 'SILVER',
    city: 'Harare',
    annualBenefit: 1800,
    benefitUsed: 923.00,
    conditions: ['Hypertension'],
    phone: '+263 71 441 2090',
    email: 'j.chikwanda@email.co.zw',
    dateOfBirth: '1972-11-08',
  },
  {
    id: 'mem-003',
    memberNumber: 'CIM-0882341',
    name: 'Mary Dzivaguru',
    plan: 'GOLD',
    city: 'Harare',
    annualBenefit: 2500,
    benefitUsed: 1102.50,
    conditions: ['Hypertension'],
    phone: '+263 78 882 3410',
    email: 'mary.dzivaguru@email.co.zw',
    dateOfBirth: '1968-07-22',
  },
];

// ─── Providers ────────────────────────────────────────────────────────────────

export const PROVIDERS: Provider[] = [
  {
    id: 'prov-001',
    code: 'PROV-BYO-00441',
    name: 'City Pharmacy Bulawayo',
    type: 'PHARMACY',
    city: 'Bulawayo',
    trustScore: 81,
    badge: 'STANDARD',
    shortfallIndex: 1.71,
    disputeRate: 8.3,
    flags90d: 14,
    totalClaims: 847,
    averageClaimValue: 62.40,
    phone: '+263 29 2882 441',
    address: '12 Fort Street, Bulawayo CBD',
    registrationDate: '2019-03-01',
    lastAuditDate: '2025-09-15',
  },
  {
    id: 'prov-002',
    code: 'PROV-HRE-00187',
    name: 'Harare Medical Centre GP',
    type: 'GP',
    city: 'Harare',
    trustScore: 73,
    badge: 'STANDARD',
    shortfallIndex: 2.08,
    disputeRate: 2.1,
    flags90d: 7,
    totalClaims: 1203,
    averageClaimValue: 48.60,
    phone: '+263 24 2700 187',
    address: '45 Samora Machel Ave, Harare',
    registrationDate: '2017-06-15',
    lastAuditDate: '2025-11-20',
  },
  {
    id: 'prov-003',
    code: 'PROV-HRE-00023',
    name: 'Avenues Pharmacy Harare',
    type: 'PHARMACY',
    city: 'Harare',
    trustScore: 97,
    badge: 'VERIFIED',
    shortfallIndex: 0.95,
    disputeRate: 0,
    flags90d: 0,
    totalClaims: 3412,
    averageClaimValue: 38.20,
    phone: '+263 24 2720 023',
    address: '2 Baines Ave, Harare Avenues',
    registrationDate: '2015-01-10',
    lastAuditDate: '2026-01-05',
  },
  {
    id: 'prov-004',
    code: 'PROV-GWE-00312',
    name: 'QuickCare Pharmacy Gweru',
    type: 'PHARMACY',
    city: 'Gweru',
    trustScore: 78,
    badge: 'STANDARD',
    shortfallIndex: 1.10,
    disputeRate: 3.1,
    flags90d: 3,
    totalClaims: 562,
    averageClaimValue: 41.80,
    phone: '+263 25 4312 000',
    address: '8 Robert Mugabe Way, Gweru',
    registrationDate: '2020-08-22',
    lastAuditDate: '2025-07-30',
  },
  {
    id: 'prov-005',
    code: 'PROV-HRE-00098',
    name: 'St Annes Hospital',
    type: 'HOSPITAL',
    city: 'Harare',
    trustScore: 91,
    badge: 'VERIFIED',
    shortfallIndex: 1.02,
    disputeRate: 0.8,
    flags90d: 2,
    totalClaims: 4821,
    averageClaimValue: 285.00,
    phone: '+263 24 2704 765',
    address: '3 Churchill Ave, Harare',
    registrationDate: '2010-05-12',
    lastAuditDate: '2026-02-14',
  },
  {
    id: 'prov-006',
    code: 'PROV-HRE-00445',
    name: 'Parirenyatwa Specialists Clinic',
    type: 'SPECIALIST',
    city: 'Harare',
    trustScore: 44,
    badge: 'REVIEW',
    shortfallIndex: 3.21,
    disputeRate: 14.7,
    flags90d: 31,
    totalClaims: 398,
    averageClaimValue: 124.50,
    phone: '+263 24 2794 111',
    address: '1 Mazowe St, Parirenyatwa, Harare',
    registrationDate: '2018-09-01',
    lastAuditDate: '2025-06-01',
  },
];

// ─── Claims ───────────────────────────────────────────────────────────────────

export const CLAIMS: Claim[] = [
  // Scenario 1: Ghost Prescription
  {
    id: 'clm-001',
    claimRef: 'CG-00291',
    nh263Ref: 'NH263-2026-0044821',
    memberId: 'mem-001',
    member: MEMBERS[0],
    providerId: 'prov-001',
    provider: PROVIDERS[0],
    serviceDate: '2026-06-28',
    submittedAt: '2026-06-30T18:42:00Z',
    claimedAmount: 88.00,
    memberShortfall: 22.00,
    expectedShortfall: [12, 18],
    riskScore: 89,
    riskLevel: 'CRITICAL',
    decision: 'PEND_INVESTIGATE',
    flags: ['PRESCRIPTION_DATE_AFTER_SERVICE', 'CHRONIC_DRUG_NO_CONDITION_REGISTERED', 'HIGH_VALUE_NO_BIOMETRIC'],
    items: [
      { id: 'itm-001', description: 'Insulin Human 100U/mL', quantity: 2, unitPrice: 19.00, total: 38.00, nappiCode: '726125001' },
      { id: 'itm-002', description: 'Metformin 500mg × 30', quantity: 1, unitPrice: 12.00, total: 12.00, nappiCode: '726044001' },
      { id: 'itm-003', description: 'Glibenclamide 5mg × 30', quantity: 1, unitPrice: 18.00, total: 18.00, nappiCode: '726098001' },
      { id: 'itm-004', description: 'Lisinopril 10mg × 30', quantity: 1, unitPrice: 20.00, total: 20.00, nappiCode: '726101001' },
    ],
    aiExplanation: 'Prescription was written 3 days after medication was dispensed. Member Tendai Moyo has no diabetes registration on file, yet three chronic diabetic medications were dispensed. No biometric confirmation was captured for a high-value transaction.',
    shapContributions: [
      { feature: 'Prescription date vs service date', contribution: 0.42, direction: 'positive' },
      { feature: 'Chronic condition not registered', contribution: 0.31, direction: 'positive' },
      { feature: 'Biometric confirmation absent', contribution: 0.18, direction: 'positive' },
      { feature: 'Claim value vs member history', contribution: 0.09, direction: 'positive' },
    ],
    latencyMs: 680,
    priority: 'CRITICAL',
    memberNotificationSent: true,
    memberNotificationChannel: 'WHATSAPP',
    memberResponse: 'DISPUTED',
    slaDeadline: '2026-07-02T18:42:00Z',
    timeline: [
      { id: 'tl-001', timestamp: '2026-06-30T18:42:00Z', event: 'Claim submitted', description: 'Claim received via NH263 webhook', actor: 'NH263 System', type: 'system' },
      { id: 'tl-002', timestamp: '2026-06-30T18:42:00Z', event: 'AI scoring initiated', description: 'FraudShield ML pipeline started', actor: 'ClaimGuard AI', type: 'system' },
      { id: 'tl-003', timestamp: '2026-06-30T18:42:00Z', event: 'Risk score: 89', description: 'High risk score — decision: PEND_INVESTIGATE', actor: 'ClaimGuard AI', type: 'system' },
      { id: 'tl-004', timestamp: '2026-06-30T18:42:03Z', event: 'WhatsApp sent', description: 'MemberGuard notification dispatched to Tendai Moyo', actor: 'MemberGuard', type: 'system' },
      { id: 'tl-005', timestamp: '2026-06-30T18:43:12Z', event: 'Member disputed', description: 'Tendai replied "2 — Something is wrong"', actor: 'Tendai Moyo', type: 'member' },
      { id: 'tl-006', timestamp: '2026-06-30T18:43:14Z', event: 'Status updated', description: 'Claim status changed to MEMBER_DISPUTED', actor: 'ClaimGuard System', type: 'system' },
    ],
  },
  // Scenario 2: Shortfall Inflation
  {
    id: 'clm-002',
    claimRef: 'CG-00441',
    nh263Ref: 'NH263-2026-0044799',
    memberId: 'mem-002',
    member: MEMBERS[1],
    providerId: 'prov-002',
    provider: PROVIDERS[1],
    serviceDate: '2026-06-30',
    submittedAt: '2026-06-30T14:18:00Z',
    claimedAmount: 45.00,
    memberShortfall: 25.00,
    expectedShortfall: [8, 12],
    riskScore: 67,
    riskLevel: 'HIGH',
    decision: 'PEND_VERIFY',
    flags: ['SHORTFALL_INFLATION_SUSPECTED'],
    items: [
      { id: 'itm-005', description: 'GP Consultation', quantity: 1, unitPrice: 45.00, total: 45.00, icd10Code: 'I10' },
    ],
    aiExplanation: 'The member shortfall of $25 is significantly above the expected range of $8–$12 for a standard GP consultation at this provider tier. This pattern has been observed 4 times in the past 90 days at this provider.',
    shapContributions: [
      { feature: 'Shortfall vs expected range', contribution: 0.58, direction: 'positive' },
      { feature: 'Provider shortfall pattern', contribution: 0.24, direction: 'positive' },
      { feature: 'Member benefit utilisation', contribution: 0.18, direction: 'negative' },
    ],
    latencyMs: 420,
    priority: 'HIGH',
    autoApproveAt: '2026-07-01T14:18:00Z',
    memberNotificationSent: true,
    memberNotificationChannel: 'WHATSAPP',
    memberResponse: 'PENDING',
    slaDeadline: '2026-07-03T14:18:00Z',
    timeline: [
      { id: 'tl-007', timestamp: '2026-06-30T14:18:00Z', event: 'Claim submitted', description: 'Claim received via NH263 webhook', actor: 'NH263 System', type: 'system' },
      { id: 'tl-008', timestamp: '2026-06-30T14:18:00Z', event: 'Risk score: 67', description: 'Moderate-high risk — PEND_VERIFY', actor: 'ClaimGuard AI', type: 'system' },
      { id: 'tl-009', timestamp: '2026-06-30T14:18:01Z', event: 'WhatsApp sent', description: 'Verification request sent to Joseph Chikwanda', actor: 'MemberGuard', type: 'system' },
    ],
  },
  // Scenario 3: Clean Claim
  {
    id: 'clm-003',
    claimRef: 'CG-00882',
    nh263Ref: 'NH263-2026-0044805',
    memberId: 'mem-003',
    member: MEMBERS[2],
    providerId: 'prov-003',
    provider: PROVIDERS[2],
    serviceDate: '2026-06-30',
    submittedAt: '2026-06-30T09:05:00Z',
    claimedAmount: 22.00,
    approvedAmount: 22.00,
    memberShortfall: 8.00,
    expectedShortfall: [7, 12],
    riskScore: 18,
    riskLevel: 'LOW',
    decision: 'APPROVE',
    flags: [],
    items: [
      { id: 'itm-006', description: 'Amlodipine 5mg × 30', quantity: 1, unitPrice: 14.00, total: 14.00, nappiCode: '726200001' },
      { id: 'itm-007', description: 'Hydrochlorothiazide 12.5mg × 30', quantity: 1, unitPrice: 8.00, total: 8.00, nappiCode: '726201001' },
    ],
    aiExplanation: 'This claim meets all verification criteria. The medications are consistent with the member\'s registered hypertension condition. Shortfall is within the expected range. Provider Avenues Pharmacy Harare has a TrustScore of 97 with zero dispute history.',
    shapContributions: [
      { feature: 'Condition matches medication', contribution: -0.35, direction: 'negative' },
      { feature: 'Provider TrustScore 97', contribution: -0.28, direction: 'negative' },
      { feature: 'Shortfall within range', contribution: -0.25, direction: 'negative' },
      { feature: 'Member claim history consistent', contribution: -0.12, direction: 'negative' },
    ],
    latencyMs: 310,
    priority: 'LOW',
    memberNotificationSent: false,
    memberResponse: 'CONFIRMED',
    slaDeadline: '2026-07-03T09:05:00Z',
    timeline: [
      { id: 'tl-010', timestamp: '2026-06-30T09:05:00Z', event: 'Claim submitted', description: 'Claim received via NH263 webhook', actor: 'NH263 System', type: 'system' },
      { id: 'tl-011', timestamp: '2026-06-30T09:05:00Z', event: 'Risk score: 18', description: 'Low risk — auto-approved', actor: 'ClaimGuard AI', type: 'system' },
      { id: 'tl-012', timestamp: '2026-06-30T09:05:00Z', event: 'Claim approved', description: 'Payment instruction sent to NH263', actor: 'ClaimGuard System', type: 'system' },
    ],
  },
  // Additional queue items
  {
    id: 'clm-004',
    claimRef: 'CG-00112',
    nh263Ref: 'NH263-2026-0044700',
    memberId: 'mem-001',
    member: MEMBERS[0],
    providerId: 'prov-006',
    provider: PROVIDERS[5],
    serviceDate: '2026-06-29',
    submittedAt: '2026-06-29T16:22:00Z',
    claimedAmount: 180.00,
    memberShortfall: 85.00,
    expectedShortfall: [30, 50],
    riskScore: 94,
    riskLevel: 'CRITICAL',
    decision: 'PEND_INVESTIGATE',
    flags: ['STATISTICAL_ANOMALY_DETECTED', 'POTENTIAL_FRAUD_SYNDICATE_DETECTED', 'HIGH_VALUE_NO_BIOMETRIC'],
    items: [
      { id: 'itm-008', description: 'Specialist Consultation', quantity: 1, unitPrice: 120.00, total: 120.00 },
      { id: 'itm-009', description: 'Lab Panel CBC + Lipids', quantity: 1, unitPrice: 60.00, total: 60.00 },
    ],
    aiExplanation: 'Multiple syndicate signals detected. This provider has 31 flags in 90 days. Member shortfall is 70% above expected. Statistical pattern matches 3 other members flagged this week.',
    shapContributions: [
      { feature: 'Syndicate pattern match', contribution: 0.45, direction: 'positive' },
      { feature: 'Provider flag frequency', contribution: 0.32, direction: 'positive' },
      { feature: 'Shortfall deviation', contribution: 0.23, direction: 'positive' },
    ],
    latencyMs: 512,
    priority: 'CRITICAL',
    memberNotificationSent: true,
    memberNotificationChannel: 'WHATSAPP',
    memberResponse: 'PENDING',
    slaDeadline: '2026-07-01T16:22:00Z',
    timeline: [
      { id: 'tl-013', timestamp: '2026-06-29T16:22:00Z', event: 'Claim submitted', description: 'Claim received via NH263', actor: 'NH263 System', type: 'system' },
      { id: 'tl-014', timestamp: '2026-06-29T16:22:01Z', event: 'Risk score: 94', description: 'CRITICAL — PEND_INVESTIGATE', actor: 'ClaimGuard AI', type: 'system' },
    ],
  },
  {
    id: 'clm-005',
    claimRef: 'CG-00088',
    nh263Ref: 'NH263-2026-0044680',
    memberId: 'mem-002',
    member: MEMBERS[1],
    providerId: 'prov-004',
    provider: PROVIDERS[3],
    serviceDate: '2026-06-28',
    submittedAt: '2026-06-28T11:10:00Z',
    claimedAmount: 35.00,
    approvedAmount: 35.00,
    memberShortfall: 6.00,
    expectedShortfall: [5, 10],
    riskScore: 22,
    riskLevel: 'LOW',
    decision: 'APPROVE',
    flags: [],
    items: [
      { id: 'itm-010', description: 'Atenolol 50mg × 30', quantity: 1, unitPrice: 18.00, total: 18.00 },
      { id: 'itm-011', description: 'Aspirin 100mg × 30', quantity: 1, unitPrice: 9.00, total: 9.00 },
      { id: 'itm-012', description: 'Dispensing fee', quantity: 1, unitPrice: 8.00, total: 8.00 },
    ],
    aiExplanation: 'Clean claim. Medications align with registered hypertension condition. Provider TrustScore 78 is within acceptable range.',
    shapContributions: [
      { feature: 'Condition registered matches Rx', contribution: -0.40, direction: 'negative' },
      { feature: 'Claim value within norms', contribution: -0.35, direction: 'negative' },
      { feature: 'Provider history acceptable', contribution: -0.25, direction: 'negative' },
    ],
    latencyMs: 290,
    priority: 'LOW',
    memberNotificationSent: false,
    memberResponse: 'CONFIRMED',
    slaDeadline: '2026-07-01T11:10:00Z',
    timeline: [
      { id: 'tl-015', timestamp: '2026-06-28T11:10:00Z', event: 'Claim submitted', description: 'Received via NH263', actor: 'NH263 System', type: 'system' },
      { id: 'tl-016', timestamp: '2026-06-28T11:10:00Z', event: 'Auto-approved', description: 'Risk score 22 — auto-approved', actor: 'ClaimGuard AI', type: 'system' },
    ],
  },
];

// ─── Dashboard Metrics ────────────────────────────────────────────────────────

export const DASHBOARD_METRICS: DashboardMetrics = {
  claimsToday: 4291,
  flaggedToday: 47,
  estimatedSaved: 3841,
  memberAlerts: 3,
  pendingInvestigation: 12,
  autoApprovedToday: 4198,
  avgLatencyMs: 387,
  detectionRate: 94.2,
};

// ─── Savings Data ─────────────────────────────────────────────────────────────

export const SAVINGS_DATA: SavingsDataPoint[] = [
  { month: 'Jan', savings: 24200, cumulative: 24200, target: 30000 },
  { month: 'Feb', savings: 31800, cumulative: 56000, target: 60000 },
  { month: 'Mar', savings: 28400, cumulative: 84400, target: 90000 },
  { month: 'Apr', savings: 41200, cumulative: 125600, target: 120000 },
  { month: 'May', savings: 38900, cumulative: 164500, target: 150000 },
  { month: 'Jun', savings: 51400, cumulative: 215900, target: 180000 },
  { month: 'Jul', savings: 0, cumulative: 0, target: 210000 },
  { month: 'Aug', savings: 0, cumulative: 0, target: 240000 },
  { month: 'Sep', savings: 0, cumulative: 0, target: 270000 },
];

// ─── USSD Stats ───────────────────────────────────────────────────────────────

export const USSD_STATS: USSDStats = {
  totalSessions: 47,
  confirmations: 12,
  disputes: 3,
  completed: 32,
  carriers: {
    econet: 23,
    netone: 15,
    telecel: 9,
  },
};

// ─── Demo Scenarios ───────────────────────────────────────────────────────────

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'ghost-prescription',
    name: 'Ghost Prescription',
    description: 'Diabetes medications dispensed without condition registration. Prescription dated 3 days after service.',
    memberName: 'Tendai Moyo',
    providerName: 'City Pharmacy Bulawayo',
    amount: 88.00,
    expectedRiskScore: 89,
    expectedDecision: 'PEND_INVESTIGATE',
    expectedLatency: 680,
    flags: ['PRESCRIPTION_DATE_AFTER_SERVICE', 'CHRONIC_DRUG_NO_CONDITION_REGISTERED', 'HIGH_VALUE_NO_BIOMETRIC'],
    color: 'red',
  },
  {
    id: 'shortfall-inflation',
    name: 'Shortfall Inflation',
    description: 'GP consultation shortfall of $25 — nearly 3× the expected $8–$12 range for this service tier.',
    memberName: 'Joseph Chikwanda',
    providerName: 'Harare Medical Centre GP',
    amount: 45.00,
    expectedRiskScore: 67,
    expectedDecision: 'PEND_VERIFY',
    expectedLatency: 420,
    flags: ['SHORTFALL_INFLATION_SUSPECTED'],
    color: 'amber',
  },
  {
    id: 'clean-claim',
    name: 'Clean Claim ✓',
    description: 'Blood pressure medications for a registered hypertension patient at a VERIFIED pharmacy. Auto-approved.',
    memberName: 'Mary Dzivaguru',
    providerName: 'Avenues Pharmacy Harare',
    amount: 22.00,
    expectedRiskScore: 18,
    expectedDecision: 'APPROVE',
    expectedLatency: 310,
    flags: [],
    color: 'green',
  },
];

// ─── Recent Live Feed Items ───────────────────────────────────────────────────

export const LIVE_FEED_CLAIMS = CLAIMS.slice(0, 5);

// ─── Trust Score Ranks ────────────────────────────────────────────────────────

export function getTrustBadge(score: number): TrustBadge {
  if (score >= 90) return 'VERIFIED';
  if (score >= 70) return 'STANDARD';
  if (score >= 50) return 'CAUTION';
  return 'REVIEW';
}
